title: <p align="center"> Nikita Sakore </p>
logo: /assets/img/NikitaS.jpg

description:
  <p align="center">  
  <a href="https://https://github.com/NikitaSakore">GitHub</a>  
  <br>  <p> 
   I'm working on Data Science, Machine learning & NLP related problems.</br></p>
  <p>
  <br>Created solution driven views and dashboards.</br>  </p>
  <p>
  Generated Interactive Dashboard in Tableau and Published the reports in Tableau Online
  
  <br>
  </p>



theme: jekyll-theme-minimal
