title: <p align="center"> Nikita Sakore </p>
logo: /assets/img/NikitaS.jpg

description:
  <p align="center">
  <a href="pdf/resume.pdf">Resume</a> |
 
  <a href="https://github.com/NikitaSakore">GitHub</a>
  
  <br>   
  
  I'm working on Data Science, Machine learning & NLP related problems.</br>
  
  <br>creating solution driven views and dashboards by developing different chart types 
  
  Generating Interactive Dashboard in Tableau and Publishing the reports in Tableau Online
  
  <br>
  </p>



theme: jekyll-theme-minimal
